export const ActionConstants = {
	LOADING:"LOADING",
	STOP_LOADING:"STOP_LOADING",
	REGISTER_SUCCESS:"REGISTER_SUCCESS",
	REGISTER_FAILED:"REGISTER_FAILED",
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAILED:"LOGIN_FAILED",
	LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
	LOGOUT_FAILED:"LOGOUT_FAILED",
	FETCH_SUCCESS:"FETCH_SUCCESS",
	FETCH_FAILED:"FETCH_FAILED",
	ADD_SUCCESS:"ADD_SUCCESS",
	ADD_FAILED:"ADD_FAILED",
	REMOVE_SUCCESS:"REMOVE_SUCCESS",
	REMOVE_FAILED:"REMOVE_FAILED"
}